//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAjax.UserControls {
    
    
    public partial class WebForm2 {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new TestAjax.UserControls.Site1 Master {
            get {
                return ((TestAjax.UserControls.Site1)(base.Master));
            }
        }
    }
}
